In [1]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [3]:
import numpy as np

In [4]:
r = np.array(revenue)

In [5]:
r

array([14574.49,  7606.46,  8611.41,  9175.41,  8058.65,  8105.44,
       11496.28,  9766.09, 10305.32, 14379.96, 10713.97, 15433.5 ])

In [6]:
e = np.array(expenses)

In [7]:
e

array([12051.82,  5695.07, 12319.2 , 12089.72,  8658.57,   840.2 ,
        3285.73,  5821.12,  6976.93, 16618.61, 10054.37,  3803.96])

In [8]:
profit = r - e

In [9]:
profit

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [10]:
profit_after_tax = profit * 0.7

In [11]:
profit_after_tax

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [14]:
profit_margin_per_month = ( profit_after_tax / r ) * 100 

In [15]:
profit_margin_per_month

array([ 12.11616324,  17.58995643, -30.13969838, -22.23352417,
        -5.21109615,  62.74388559,  49.99343266,  28.27619856,
        22.60844884, -10.89749207,   4.30951365,  52.74680403])

In [16]:
mean_of_year = profit_after_tax.mean()

In [17]:
mean_of_year

1750.6813333333332

In [18]:
good_months = profit_after_tax > mean_of_year

In [19]:
good_months

array([ True, False, False, False, False,  True,  True,  True,  True,
       False, False,  True])

In [20]:
bad_months = profit_after_tax < mean_of_year

In [21]:
bad_months

array([False,  True,  True,  True,  True, False, False, False, False,
        True,  True, False])

In [26]:
best_month = profit_after_tax.max

In [27]:
best_month

<function ndarray.max>

In [28]:
bm = best_month()

In [29]:
bm

8140.678

In [30]:
worst_month = profit_after_tax.min()

In [31]:
worst_month

-2595.4530000000004

In [33]:
profit.astype(int)

array([ 2522,  1911, -3707, -2914,  -599,  7265,  8210,  3944,  3328,
       -2238,   659, 11629])

In [37]:
profit.round()

array([ 2523.,  1911., -3708., -2914.,  -600.,  7265.,  8211.,  3945.,
        3328., -2239.,   660., 11630.])

In [35]:
profit_after_tax.astype(int)

array([ 1765,  1337, -2595, -2040,  -419,  5085,  5747,  2761,  2329,
       -1567,   461,  8140])

In [39]:
profit_margin_per_month.round(2)

array([ 12.12,  17.59, -30.14, -22.23,  -5.21,  62.74,  49.99,  28.28,
        22.61, -10.9 ,   4.31,  52.75])

In [46]:
best_month_year = profit_after_tax == (profit_after_tax.max())

In [47]:
best_month_year

array([False, False, False, False, False, False, False, False, False,
       False, False,  True])

In [42]:
profit_after_tax.max()

8140.678

In [43]:
profit_after_tax

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [48]:
worst_month_year = profit_after_tax == profit_after_tax.min()

In [49]:
worst_month_year

array([False, False,  True, False, False, False, False, False, False,
       False, False, False])