First Problem

In [46]:
import numpy as np
from numpy.random import randn

In [52]:
counter = 0
for i in randn(1000):
    if i > -1:
        if i < 1:
            counter += 1
percent = ( counter / 1000 ) * 100
print(percent)
print('counter:', counter)

69.0
counter: 690


In [55]:
numbers = np.random.randn(100000)
counter = 0
for i in numbers:
    if i > -1 and i < 1:
        counter += 1
n = len(numbers)
percent = ( counter / n ) * 100
print(percent)
# print(numbers)
# print(counter)

68.227


In [54]:
2.5 * np.random.randn(2, 4) + 3

array([[ 3.33925187, -1.61024185,  0.32663089,  5.93147627],
       [ 4.93776368,  3.64063376, -1.2151916 ,  2.13120837]])

In [26]:
np.random.randn(1,10)

array([[-0.72364667, -1.05011223, -1.27198506, -0.49620931,  0.35833674,
         1.4547715 , -2.15712822, -1.31375024,  1.07362333,  2.76330835]])

In [16]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    If positive, int_like or int-convertible arguments are provided,
    `randn` generates an array of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1 (if any of the :math:`d_i` are
    floats, they are first converted to integers by truncation). A single
    float randomly sampled from the distribution is returned if no
    argument is provided.
    
    This is a convenience function.  If you want an interface that takes a
    tuple as the first argument, use `numpy.random.standard_normal` instead.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should be all positive.
        If no argument is given a single Python float is ret

---

Rough Work

In [56]:
a = list(range(5))

In [57]:
a

[0, 1, 2, 3, 4]

In [59]:
a[4] = "Hey"

In [60]:
a

[0, 1, 2, 3, 'Hey']

In [64]:
a.append(9) 

In [65]:
a

[0, 1, 2, 3, 'Hey', 9]

In [66]:
a.remove('Hey')

In [67]:
a

[0, 1, 2, 3, 9]

In [3]:
l = ['A','B']

In [4]:
type(l)

list

In [5]:
import scrapy

In [11]:
scrapy.version_info

(1, 6, 0)

In [23]:
import numpy as np

In [3]:
l = [2,543,74632,1324,64,75,46235,432]

In [4]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [5]:
a = np.array(l)

In [12]:
a

array([    2,   543, 74632,  1324,    64,    75, 46235,   432])

In [11]:
type(a)

numpy.ndarray

In [13]:
m = [423, 85.34, False]

In [14]:
b = np.array(m)

In [15]:
b

array([423.  ,  85.34,   0.  ])

In [16]:
type(b)

numpy.ndarray

In [17]:
b[2]

0.0

In [27]:
b = np.append(b,[True, 34.8])

In [28]:
b

array([423.  ,  85.34,   0.  ,   1.  ,   1.  ,  34.8 ])